version: 0.0
os: linux

files:
  - source: /
    destination: /etc/app

hooks:
  ApplicationStop:
    - location: scripts/stop-application.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/start-application.sh
      timeout: 120
      runas: root
