POST https://localhost:8080/api/socialNetworking/message/send
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
  "from": null,
  "to": "test2",
  "message": "heyyyy"
}

###

