insert into Country_Config(id, countryCode, externalValue) values(1, 'AF', 'Afghanistan');
insert into Country_Config(id, countryCode, externalValue) values(2, 'AL', 'Albania');
insert into Country_Config(id, countryCode, externalValue) values(3, 'DZ', 'Algeria');
insert into Country_Config(id, countryCode, externalValue) values(4, 'AS', 'American Samoa');
insert into Country_Config(id, countryCode, externalValue) values(5, 'AD', 'Andorra');
insert into Country_Config(id, countryCode, externalValue) values(6, 'AO', 'Angola');
insert into Country_Config(id, countryCode, externalValue) values(7, 'AI', 'Anguilla');
insert into Country_Config(id, countryCode, externalValue) values(8, 'AQ', 'Antarctica');
insert into Country_Config(id, countryCode, externalValue) values(9, 'AG', 'Antigua and Barbuda');
insert into Country_Config(id, countryCode, externalValue) values(10, 'AR', 'Argentina');
insert into Country_Config(id, countryCode, externalValue) values(11, 'AM', 'Armenia');
insert into Country_Config(id, countryCode, externalValue) values(12, 'AW', 'Aruba');
insert into Country_Config(id, countryCode, externalValue) values(13, 'AU', 'Australia');
insert into Country_Config(id, countryCode, externalValue) values(14, 'AT', 'Austria');
insert into Country_Config(id, countryCode, externalValue) values(15, 'AZ', 'Azerbaijan');
insert into Country_Config(id, countryCode, externalValue) values(16, 'BS', 'Bahamas (the)');
insert into Country_Config(id, countryCode, externalValue) values(17, 'BH', 'Bahrain');
insert into Country_Config(id, countryCode, externalValue) values(18, 'BD', 'Bangladesh');
insert into Country_Config(id, countryCode, externalValue) values(19, 'BB', 'Barbados');
insert into Country_Config(id, countryCode, externalValue) values(20, 'BY', 'Belarus');
insert into Country_Config(id, countryCode, externalValue) values(21, 'BE', 'Belgium');
insert into Country_Config(id, countryCode, externalValue) values(22, 'BZ', 'Belize');
insert into Country_Config(id, countryCode, externalValue) values(23, 'BJ', 'Benin');
insert into Country_Config(id, countryCode, externalValue) values(24, 'BM', 'Bermuda');
insert into Country_Config(id, countryCode, externalValue) values(25, 'BT', 'Bhutan');
insert into Country_Config(id, countryCode, externalValue) values(26, 'BO', 'Bolivia (Plurinational State of)');
insert into Country_Config(id, countryCode, externalValue) values(27, 'BQ', 'Bonaire, Sint Eustatius and Saba');
insert into Country_Config(id, countryCode, externalValue) values(28, 'BA', 'Bosnia and Herzegovina');
insert into Country_Config(id, countryCode, externalValue) values(29, 'BW', 'Botswana');
insert into Country_Config(id, countryCode, externalValue) values(30, 'BV', 'Bouvet Island');
insert into Country_Config(id, countryCode, externalValue) values(31, 'BR', 'Brazil');
insert into Country_Config(id, countryCode, externalValue) values(32, 'IO', 'British Indian Ocean Territory (the)');
insert into Country_Config(id, countryCode, externalValue) values(33, 'BN', 'Brunei Darussalam');
insert into Country_Config(id, countryCode, externalValue) values(34, 'BG', 'Bulgaria');
insert into Country_Config(id, countryCode, externalValue) values(35, 'BF', 'Burkina Faso');
insert into Country_Config(id, countryCode, externalValue) values(36, 'BI', 'Burundi');
insert into Country_Config(id, countryCode, externalValue) values(37, 'CV', 'Cabo Verde');
insert into Country_Config(id, countryCode, externalValue) values(38, 'KH', 'Cambodia');
insert into Country_Config(id, countryCode, externalValue) values(39, 'CM', 'Cameroon');
insert into Country_Config(id, countryCode, externalValue) values(40, 'CA', 'Canada');
insert into Country_Config(id, countryCode, externalValue) values(41, 'KY', 'Cayman Islands (the)');
insert into Country_Config(id, countryCode, externalValue) values(42, 'CF', 'Central African Republic (the)');
insert into Country_Config(id, countryCode, externalValue) values(43, 'TD', 'Chad');
insert into Country_Config(id, countryCode, externalValue) values(44, 'CL', 'Chile');
insert into Country_Config(id, countryCode, externalValue) values(45, 'CN', 'China');
insert into Country_Config(id, countryCode, externalValue) values(46, 'CX', 'Christmas Island');
insert into Country_Config(id, countryCode, externalValue) values(47, 'CC', 'Cocos (Keeling) Islands (the)');
insert into Country_Config(id, countryCode, externalValue) values(48, 'CO', 'Colombia');
insert into Country_Config(id, countryCode, externalValue) values(49, 'KM', 'Comoros (the)');
insert into Country_Config(id, countryCode, externalValue) values(50, 'CD', 'Congo (the Democratic Republic of the)');
insert into Country_Config(id, countryCode, externalValue) values(51, 'CG', 'Congo (the)');
insert into Country_Config(id, countryCode, externalValue) values(52, 'CK', 'Cook Islands (the)');
insert into Country_Config(id, countryCode, externalValue) values(53, 'CR', 'Costa Rica');
insert into Country_Config(id, countryCode, externalValue) values(54, 'HR', 'Croatia');
insert into Country_Config(id, countryCode, externalValue) values(55, 'CU', 'Cuba');
insert into Country_Config(id, countryCode, externalValue) values(56, 'CW', 'Curaçao');
insert into Country_Config(id, countryCode, externalValue) values(57, 'CY', 'Cyprus');
insert into Country_Config(id, countryCode, externalValue) values(58, 'CZ', 'Czechia');
insert into Country_Config(id, countryCode, externalValue) values(59, 'CI', 'Côte d''Ivoire');
insert into Country_Config(id, countryCode, externalValue) values(60, 'DK', 'Denmark');
insert into Country_Config(id, countryCode, externalValue) values(61, 'DJ', 'Djibouti');
insert into Country_Config(id, countryCode, externalValue) values(62, 'DM', 'Dominica');
insert into Country_Config(id, countryCode, externalValue) values(63, 'DO', 'Dominican Republic (the)');
insert into Country_Config(id, countryCode, externalValue) values(64, 'EC', 'Ecuador');
insert into Country_Config(id, countryCode, externalValue) values(65, 'EG', 'Egypt');
insert into Country_Config(id, countryCode, externalValue) values(66, 'SV', 'El Salvador');
insert into Country_Config(id, countryCode, externalValue) values(67, 'GQ', 'Equatorial Guinea');
insert into Country_Config(id, countryCode, externalValue) values(68, 'ER', 'Eritrea');
insert into Country_Config(id, countryCode, externalValue) values(69, 'EE', 'Estonia');
insert into Country_Config(id, countryCode, externalValue) values(70, 'SZ', 'Eswatini');
insert into Country_Config(id, countryCode, externalValue) values(71, 'ET', 'Ethiopia');
insert into Country_Config(id, countryCode, externalValue) values(72, 'FK', 'Falkland Islands (the) [Malvinas]');
insert into Country_Config(id, countryCode, externalValue) values(73, 'FO', 'Faroe Islands (the)');
insert into Country_Config(id, countryCode, externalValue) values(74, 'FJ', 'Fiji');
insert into Country_Config(id, countryCode, externalValue) values(75, 'FI', 'Finland');
insert into Country_Config(id, countryCode, externalValue) values(76, 'FR', 'France');
insert into Country_Config(id, countryCode, externalValue) values(77, 'GF', 'French Guiana');
insert into Country_Config(id, countryCode, externalValue) values(78, 'PF', 'French Polynesia');
insert into Country_Config(id, countryCode, externalValue) values(79, 'TF', 'French Southern Territories (the)');
insert into Country_Config(id, countryCode, externalValue) values(80, 'GA', 'Gabon');
insert into Country_Config(id, countryCode, externalValue) values(81, 'GM', 'Gambia (the)');
insert into Country_Config(id, countryCode, externalValue) values(82, 'GE', 'Georgia');
insert into Country_Config(id, countryCode, externalValue) values(83, 'DE', 'Germany');
insert into Country_Config(id, countryCode, externalValue) values(84, 'GH', 'Ghana');
insert into Country_Config(id, countryCode, externalValue) values(85, 'GI', 'Gibraltar');
insert into Country_Config(id, countryCode, externalValue) values(86, 'GR', 'Greece');
insert into Country_Config(id, countryCode, externalValue) values(87, 'GL', 'Greenland');
insert into Country_Config(id, countryCode, externalValue) values(88, 'GD', 'Grenada');
insert into Country_Config(id, countryCode, externalValue) values(89, 'GP', 'Guadeloupe');
insert into Country_Config(id, countryCode, externalValue) values(90, 'GU', 'Guam');
insert into Country_Config(id, countryCode, externalValue) values(91, 'GT', 'Guatemala');
insert into Country_Config(id, countryCode, externalValue) values(92, 'GG', 'Guernsey');
insert into Country_Config(id, countryCode, externalValue) values(93, 'GN', 'Guinea');
insert into Country_Config(id, countryCode, externalValue) values(94, 'GW', 'Guinea-Bissau');
insert into Country_Config(id, countryCode, externalValue) values(95, 'GY', 'Guyana');
insert into Country_Config(id, countryCode, externalValue) values(96, 'HT', 'Haiti');
insert into Country_Config(id, countryCode, externalValue) values(97, 'HM', 'Heard Island and McDonald Islands');
insert into Country_Config(id, countryCode, externalValue) values(98, 'VA', 'Holy See (the)');
insert into Country_Config(id, countryCode, externalValue) values(99, 'HN', 'Honduras');
insert into Country_Config(id, countryCode, externalValue) values(100, 'HK', 'Hong Kong');
insert into Country_Config(id, countryCode, externalValue) values(101, 'HU', 'Hungary');
insert into Country_Config(id, countryCode, externalValue) values(102, 'IS', 'Iceland');
insert into Country_Config(id, countryCode, externalValue) values(103, 'IN', 'India');
insert into Country_Config(id, countryCode, externalValue) values(104, 'ID', 'Indonesia');
insert into Country_Config(id, countryCode, externalValue) values(105, 'IR', 'Iran (Islamic Republic of)');
insert into Country_Config(id, countryCode, externalValue) values(106, 'IQ', 'Iraq');
insert into Country_Config(id, countryCode, externalValue) values(107, 'IE', 'Ireland');
insert into Country_Config(id, countryCode, externalValue) values(108, 'IM', 'Isle of Man');
insert into Country_Config(id, countryCode, externalValue) values(109, 'IL', 'Israel');
insert into Country_Config(id, countryCode, externalValue) values(110, 'IT', 'Italy');
insert into Country_Config(id, countryCode, externalValue) values(111, 'JM', 'Jamaica');
insert into Country_Config(id, countryCode, externalValue) values(112, 'JP', 'Japan');
insert into Country_Config(id, countryCode, externalValue) values(113, 'JE', 'Jersey');
insert into Country_Config(id, countryCode, externalValue) values(114, 'JO', 'Jordan');
insert into Country_Config(id, countryCode, externalValue) values(115, 'KZ', 'Kazakhstan');
insert into Country_Config(id, countryCode, externalValue) values(116, 'KE', 'Kenya');
insert into Country_Config(id, countryCode, externalValue) values(117, 'KI', 'Kiribati');
insert into Country_Config(id, countryCode, externalValue) values(118, 'KP', 'Korea (the Democratic People''s Republic of)');
insert into Country_Config(id, countryCode, externalValue) values(119, 'KR', 'Korea (the Republic of)');
insert into Country_Config(id, countryCode, externalValue) values(120, 'KW', 'Kuwait');
insert into Country_Config(id, countryCode, externalValue) values(121, 'KG', 'Kyrgyzstan');
insert into Country_Config(id, countryCode, externalValue) values(122, 'LA', 'Lao People''s Democratic Republic (the)');
insert into Country_Config(id, countryCode, externalValue) values(123, 'LV', 'Latvia');
insert into Country_Config(id, countryCode, externalValue) values(124, 'LB', 'Lebanon');
insert into Country_Config(id, countryCode, externalValue) values(125, 'LS', 'Lesotho');
insert into Country_Config(id, countryCode, externalValue) values(126, 'LR', 'Liberia');
insert into Country_Config(id, countryCode, externalValue) values(127, 'LY', 'Libya');
insert into Country_Config(id, countryCode, externalValue) values(128, 'LI', 'Liechtenstein');
insert into Country_Config(id, countryCode, externalValue) values(129, 'LT', 'Lithuania');
insert into Country_Config(id, countryCode, externalValue) values(130, 'LU', 'Luxembourg');
insert into Country_Config(id, countryCode, externalValue) values(131, 'MO', 'Macao');
insert into Country_Config(id, countryCode, externalValue) values(132, 'MG', 'Madagascar');
insert into Country_Config(id, countryCode, externalValue) values(133, 'MW', 'Malawi');
insert into Country_Config(id, countryCode, externalValue) values(134, 'MY', 'Malaysia');
insert into Country_Config(id, countryCode, externalValue) values(135, 'MV', 'Maldives');
insert into Country_Config(id, countryCode, externalValue) values(136, 'ML', 'Mali');
insert into Country_Config(id, countryCode, externalValue) values(137, 'MT', 'Malta');
insert into Country_Config(id, countryCode, externalValue) values(138, 'MH', 'Marshall Islands (the)');
insert into Country_Config(id, countryCode, externalValue) values(139, 'MQ', 'Martinique');
insert into Country_Config(id, countryCode, externalValue) values(140, 'MR', 'Mauritania');
insert into Country_Config(id, countryCode, externalValue) values(141, 'MU', 'Mauritius');
insert into Country_Config(id, countryCode, externalValue) values(142, 'YT', 'Mayotte');
insert into Country_Config(id, countryCode, externalValue) values(143, 'MX', 'Mexico');
insert into Country_Config(id, countryCode, externalValue) values(144, 'FM', 'Micronesia (Federated States of)');
insert into Country_Config(id, countryCode, externalValue) values(145, 'MD', 'Moldova (the Republic of)');
insert into Country_Config(id, countryCode, externalValue) values(146, 'MC', 'Monaco');
insert into Country_Config(id, countryCode, externalValue) values(147, 'MN', 'Mongolia');
insert into Country_Config(id, countryCode, externalValue) values(148, 'ME', 'Montenegro');
insert into Country_Config(id, countryCode, externalValue) values(149, 'MS', 'Montserrat');
insert into Country_Config(id, countryCode, externalValue) values(150, 'MA', 'Morocco');
insert into Country_Config(id, countryCode, externalValue) values(151, 'MZ', 'Mozambique');
insert into Country_Config(id, countryCode, externalValue) values(152, 'MM', 'Myanmar');
insert into Country_Config(id, countryCode, externalValue) values(153, 'NA', 'Namibia');
insert into Country_Config(id, countryCode, externalValue) values(154, 'NR', 'Nauru');
insert into Country_Config(id, countryCode, externalValue) values(155, 'NP', 'Nepal');
insert into Country_Config(id, countryCode, externalValue) values(156, 'NL', 'Netherlands (the)');
insert into Country_Config(id, countryCode, externalValue) values(157, 'NC', 'New Caledonia');
insert into Country_Config(id, countryCode, externalValue) values(158, 'NZ', 'New Zealand');
insert into Country_Config(id, countryCode, externalValue) values(159, 'NI', 'Nicaragua');
insert into Country_Config(id, countryCode, externalValue) values(160, 'NE', 'Niger (the)');
insert into Country_Config(id, countryCode, externalValue) values(161, 'NG', 'Nigeria');
insert into Country_Config(id, countryCode, externalValue) values(162, 'NU', 'Niue');
insert into Country_Config(id, countryCode, externalValue) values(163, 'NF', 'Norfolk Island');
insert into Country_Config(id, countryCode, externalValue) values(164, 'MP', 'Northern Mariana Islands (the)');
insert into Country_Config(id, countryCode, externalValue) values(165, 'NO', 'Norway');
insert into Country_Config(id, countryCode, externalValue) values(166, 'OM', 'Oman');
insert into Country_Config(id, countryCode, externalValue) values(167, 'PK', 'Pakistan');
insert into Country_Config(id, countryCode, externalValue) values(168, 'PW', 'Palau');
insert into Country_Config(id, countryCode, externalValue) values(169, 'PS', 'Palestine, State of');
insert into Country_Config(id, countryCode, externalValue) values(170, 'PA', 'Panama');
insert into Country_Config(id, countryCode, externalValue) values(171, 'PG', 'Papua New Guinea');
insert into Country_Config(id, countryCode, externalValue) values(172, 'PY', 'Paraguay');
insert into Country_Config(id, countryCode, externalValue) values(173, 'PE', 'Peru');
insert into Country_Config(id, countryCode, externalValue) values(174, 'PH', 'Philippines (the)');
insert into Country_Config(id, countryCode, externalValue) values(175, 'PN', 'Pitcairn');
insert into Country_Config(id, countryCode, externalValue) values(176, 'PL', 'Poland');
insert into Country_Config(id, countryCode, externalValue) values(177, 'PT', 'Portugal');
insert into Country_Config(id, countryCode, externalValue) values(178, 'PR', 'Puerto Rico');
insert into Country_Config(id, countryCode, externalValue) values(179, 'QA', 'Qatar');
insert into Country_Config(id, countryCode, externalValue) values(180, 'MK', 'Republic of North Macedonia');
insert into Country_Config(id, countryCode, externalValue) values(181, 'RO', 'Romania');
insert into Country_Config(id, countryCode, externalValue) values(182, 'RU', 'Russian Federation (the)');
insert into Country_Config(id, countryCode, externalValue) values(183, 'RW', 'Rwanda');
insert into Country_Config(id, countryCode, externalValue) values(184, 'RE', 'Réunion');
insert into Country_Config(id, countryCode, externalValue) values(185, 'BL', 'Saint Barthélemy');
insert into Country_Config(id, countryCode, externalValue) values(186, 'SH', 'Saint Helena, Ascension and Tristan da Cunha');
insert into Country_Config(id, countryCode, externalValue) values(187, 'KN', 'Saint Kitts and Nevis');
insert into Country_Config(id, countryCode, externalValue) values(188, 'LC', 'Saint Lucia');
insert into Country_Config(id, countryCode, externalValue) values(189, 'MF', 'Saint Martin (French part)');
insert into Country_Config(id, countryCode, externalValue) values(190, 'PM', 'Saint Pierre and Miquelon');
insert into Country_Config(id, countryCode, externalValue) values(191, 'VC', 'Saint Vincent and the Grenadines');
insert into Country_Config(id, countryCode, externalValue) values(192, 'WS', 'Samoa');
insert into Country_Config(id, countryCode, externalValue) values(193, 'SM', 'San Marino');
insert into Country_Config(id, countryCode, externalValue) values(194, 'ST', 'Sao Tome and Principe');
insert into Country_Config(id, countryCode, externalValue) values(195, 'SA', 'Saudi Arabia');
insert into Country_Config(id, countryCode, externalValue) values(196, 'SN', 'Senegal');
insert into Country_Config(id, countryCode, externalValue) values(197, 'RS', 'Serbia');
insert into Country_Config(id, countryCode, externalValue) values(198, 'SC', 'Seychelles');
insert into Country_Config(id, countryCode, externalValue) values(199, 'SL', 'Sierra Leone');
insert into Country_Config(id, countryCode, externalValue) values(200, 'SG', 'Singapore');
insert into Country_Config(id, countryCode, externalValue) values(201, 'SX', 'Sint Maarten (Dutch part)');
insert into Country_Config(id, countryCode, externalValue) values(202, 'SK', 'Slovakia');
insert into Country_Config(id, countryCode, externalValue) values(203, 'SI', 'Slovenia');
insert into Country_Config(id, countryCode, externalValue) values(204, 'SB', 'Solomon Islands');
insert into Country_Config(id, countryCode, externalValue) values(205, 'SO', 'Somalia');
insert into Country_Config(id, countryCode, externalValue) values(206, 'ZA', 'South Africa');
insert into Country_Config(id, countryCode, externalValue) values(207, 'GS', 'South Georgia and the South Sandwich Islands');
insert into Country_Config(id, countryCode, externalValue) values(208, 'SS', 'South Sudan');
insert into Country_Config(id, countryCode, externalValue) values(209, 'ES', 'Spain');
insert into Country_Config(id, countryCode, externalValue) values(210, 'LK', 'Sri Lanka');
insert into Country_Config(id, countryCode, externalValue) values(211, 'SD', 'Sudan (the)');
insert into Country_Config(id, countryCode, externalValue) values(212, 'SR', 'Suriname');
insert into Country_Config(id, countryCode, externalValue) values(213, 'SJ', 'Svalbard and Jan Mayen');
insert into Country_Config(id, countryCode, externalValue) values(214, 'SE', 'Sweden');
insert into Country_Config(id, countryCode, externalValue) values(215, 'CH', 'Switzerland');
insert into Country_Config(id, countryCode, externalValue) values(216, 'SY', 'Syrian Arab Republic');
insert into Country_Config(id, countryCode, externalValue) values(217, 'TW', 'Taiwan');
insert into Country_Config(id, countryCode, externalValue) values(218, 'TJ', 'Tajikistan');
insert into Country_Config(id, countryCode, externalValue) values(219, 'TZ', 'Tanzania, United Republic of');
insert into Country_Config(id, countryCode, externalValue) values(220, 'TH', 'Thailand');
insert into Country_Config(id, countryCode, externalValue) values(221, 'TL', 'Timor-Leste');
insert into Country_Config(id, countryCode, externalValue) values(222, 'TG', 'Togo');
insert into Country_Config(id, countryCode, externalValue) values(223, 'TK', 'Tokelau');
insert into Country_Config(id, countryCode, externalValue) values(224, 'TO', 'Tonga');
insert into Country_Config(id, countryCode, externalValue) values(225, 'TT', 'Trinidad and Tobago');
insert into Country_Config(id, countryCode, externalValue) values(226, 'TN', 'Tunisia');
insert into Country_Config(id, countryCode, externalValue) values(227, 'TR', 'Turkey');
insert into Country_Config(id, countryCode, externalValue) values(228, 'TM', 'Turkmenistan');
insert into Country_Config(id, countryCode, externalValue) values(229, 'TC', 'Turks and Caicos Islands (the)');
insert into Country_Config(id, countryCode, externalValue) values(230, 'TV', 'Tuvalu');
insert into Country_Config(id, countryCode, externalValue) values(231, 'UG', 'Uganda');
insert into Country_Config(id, countryCode, externalValue) values(232, 'UA', 'Ukraine');
insert into Country_Config(id, countryCode, externalValue) values(233, 'AE', 'United Arab Emirates (the)');
insert into Country_Config(id, countryCode, externalValue) values(234, 'GB', 'United Kingdom of Great Britain and Northern Ireland (the)');
insert into Country_Config(id, countryCode, externalValue) values(235, 'UM', 'United States Minor Outlying Islands (the)');
insert into Country_Config(id, countryCode, externalValue) values(236, 'US', 'United States of America (the)');
insert into Country_Config(id, countryCode, externalValue) values(237, 'UY', 'Uruguay');
insert into Country_Config(id, countryCode, externalValue) values(238, 'UZ', 'Uzbekistan');
insert into Country_Config(id, countryCode, externalValue) values(239, 'VU', 'Vanuatu');
insert into Country_Config(id, countryCode, externalValue) values(240, 'VE', 'Venezuela (Bolivarian Republic of)');
insert into Country_Config(id, countryCode, externalValue) values(241, 'VN', 'Viet Nam');
insert into Country_Config(id, countryCode, externalValue) values(242, 'VG', 'Virgin Islands (British)');
insert into Country_Config(id, countryCode, externalValue) values(243, 'VI', 'Virgin Islands (U.S.)');
insert into Country_Config(id, countryCode, externalValue) values(244, 'WF', 'Wallis and Futuna');
insert into Country_Config(id, countryCode, externalValue) values(245, 'EH', 'Western Sahara');
insert into Country_Config(id, countryCode, externalValue) values(246, 'YE', 'Yemen');
insert into Country_Config(id, countryCode, externalValue) values(247, 'ZM', 'Zambia');
insert into Country_Config(id, countryCode, externalValue) values(248, 'ZW', 'Zimbabwe');
insert into Country_Config(id, countryCode, externalValue) values(249, 'AX', 'Åland Islands');